# 🔐 Replace with your keys
API_KEY = "PKHOLBEXPJSEYXS3BS63QR6MQE"
SECRET_KEY = "2sjK9ephS3nM1DpnsqMo8KbSCxnAjmiXSJojc7rLYd4u"
BASE_URL = "https://paper-api.alpaca.markets"


SYMBOLS = ["AAPL"]

POSITION_SIZE = 1
STOP_LOSS_PERCENT = 0.02
TAKE_PROFIT_PERCENT = 0.05